sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # ACCOUNT SERVICE
  - export ACCOUNT_SERVICE=afermon/piggymetrics-account-service
  - docker build -t $ACCOUNT_SERVICE:$COMMIT .
  - docker tag $ACCOUNT_SERVICE:$COMMIT $ACCOUNT_SERVICE:$TAG
  - docker push $ACCOUNT_SERVICE